<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Adilabad</name>
   <tag></tag>
   <elementGuidId>57fde29a-f04c-4bb8-a759-89752eebe553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div[4]/ul/li[7]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Adilabad&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7ccac92-3e94-4242-a8cb-4133b42ee53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bwc__sc-ttnkwg-8 fsJkBY</value>
      <webElementGuid>6c8cc636-7c8e-4968-a723-42c7e6b4e7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adilabad</value>
      <webElementGuid>8006cb28-b2e8-4425-9b8a-3ba2a1aa422b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;bwc__sc-1ihur1g-4 jxHGrI in-animation&quot;]/div[@class=&quot;bwc__sc-1ihur1g-5 gznHHe in-animation&quot;]/div[@class=&quot;bwc__sc-m1rlyj-3 bwc__sc-ttnkwg-27 kwGtup&quot;]/div[@class=&quot;bwc__sc-ttnkwg-4 Ettpg&quot;]/ul[@class=&quot;bwc__sc-ttnkwg-6 khSHCa&quot;]/li[@class=&quot;bwc__sc-ttnkwg-7 gtXMtL&quot;]/div[@class=&quot;bwc__sc-ttnkwg-8 fsJkBY&quot;]</value>
      <webElementGuid>0bb8e943-3f6a-428a-acbf-3f01d4f749f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[4]/ul/li[7]/div</value>
      <webElementGuid>7cf38d32-3020-4d6a-a4c8-c2dc93f67beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Addanki'])[1]/following::div[1]</value>
      <webElementGuid>4f27b6d5-0fad-4e02-b787-8048a7826ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acharapakkam'])[1]/following::div[2]</value>
      <webElementGuid>bf3876cd-7012-4e2a-ac3c-c3b6d59ff7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adimali'])[1]/preceding::div[1]</value>
      <webElementGuid>50ac7598-6a3f-4afc-a03b-e6dfd23905a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adipur'])[1]/preceding::div[2]</value>
      <webElementGuid>2194d6ab-6cc2-4a28-813e-5e04f2c459b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adilabad']/parent::*</value>
      <webElementGuid>d991ba44-0f4e-4afa-a53c-4c7654b85526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[7]/div</value>
      <webElementGuid>b2bc3570-5196-4c68-bb72-17d322eaf835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Adilabad' or . = 'Adilabad')]</value>
      <webElementGuid>c15b4e0d-0020-4fcf-8a5f-2f833b7f4294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
