<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ahmednagar</name>
   <tag></tag>
   <elementGuidId>ac3901e9-ae7f-4637-a8b2-136a1f3131f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div[4]/ul/li[16]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ahmednagar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22bacda5-cebc-4bf0-af5d-7c625c39cae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bwc__sc-ttnkwg-8 fsJkBY</value>
      <webElementGuid>2f2bde69-9896-4ab9-9f73-e3ddd1ec8f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ahmednagar</value>
      <webElementGuid>75168463-a636-4127-9c12-a8d3e2ebf7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;bwc__sc-1ihur1g-4 jxHGrI in-animation&quot;]/div[@class=&quot;bwc__sc-1ihur1g-5 gznHHe in-animation&quot;]/div[@class=&quot;bwc__sc-m1rlyj-3 bwc__sc-ttnkwg-27 kwGtup&quot;]/div[@class=&quot;bwc__sc-ttnkwg-4 Ettpg&quot;]/ul[@class=&quot;bwc__sc-ttnkwg-6 khSHCa&quot;]/li[@class=&quot;bwc__sc-ttnkwg-7 gtXMtL&quot;]/div[@class=&quot;bwc__sc-ttnkwg-8 fsJkBY&quot;]</value>
      <webElementGuid>e1a0130a-457a-4924-ac33-23ec4f370012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[4]/ul/li[16]/div</value>
      <webElementGuid>19177299-74b3-4181-9e28-61b27138b1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahmedgarh'])[1]/following::div[1]</value>
      <webElementGuid>f750032f-2b78-443b-900c-e3fff7dd9b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agra'])[1]/following::div[2]</value>
      <webElementGuid>ccda961f-453b-4bd4-bf44-ae941579ea93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahore'])[1]/preceding::div[1]</value>
      <webElementGuid>78908d04-7469-4bf8-b339-1cc33011bbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aizawl'])[1]/preceding::div[2]</value>
      <webElementGuid>0e1aad26-7c56-4d27-93dd-fd992c4657bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ahmednagar']/parent::*</value>
      <webElementGuid>1dc6f85d-ac37-4f45-a17a-af7bf86be3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[16]/div</value>
      <webElementGuid>cba06725-347f-41b7-bef3-2b6473b246cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ahmednagar' or . = 'Ahmednagar')]</value>
      <webElementGuid>6fd389f4-c828-4fcd-9d44-356e20fb4779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
