<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kolkata</name>
   <tag></tag>
   <elementGuidId>dc3bf52f-8ce7-453f-b413-75bdf4c871d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li[9]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kolkata&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>19760243-edb8-4b0c-a5e3-99da598cfc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bwc__sc-ttnkwg-16 dizuyr</value>
      <webElementGuid>d10f144c-8cff-439a-af4a-b4add6d320a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kolkata</value>
      <webElementGuid>d52fbad3-f790-4c31-9e56-4e2a25abd42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;bwc__sc-1ihur1g-4 jxHGrI in-animation&quot;]/div[@class=&quot;bwc__sc-1ihur1g-5 gznHHe in-animation&quot;]/div[@class=&quot;bwc__sc-m1rlyj-3 bwc__sc-ttnkwg-27 kwGtup&quot;]/div[@class=&quot;bwc__sc-ttnkwg-4 Ettpg&quot;]/ul[@class=&quot;bwc__sc-ttnkwg-15 gZrltM&quot;]/li[@class=&quot;bwc__sc-ttnkwg-18 KUowN&quot;]/div[@class=&quot;bwc__sc-ttnkwg-19 hkqhSR&quot;]/span[@class=&quot;bwc__sc-ttnkwg-16 dizuyr&quot;]</value>
      <webElementGuid>93f301c8-5ac0-4dea-82af-42c91bc0ffe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li[9]/div/span</value>
      <webElementGuid>f456cb50-d4c8-4cb2-a48b-308f476fe453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pune'])[1]/following::span[1]</value>
      <webElementGuid>304e8553-6a71-4c28-99e3-c3a089d2fb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[1]/following::span[2]</value>
      <webElementGuid>70a8fc4b-cedd-4871-bfba-c2f6ecfad4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kochi'])[1]/preceding::span[1]</value>
      <webElementGuid>dfbc3675-2516-44ce-8e42-d198f36f78e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Cities'])[1]/preceding::span[2]</value>
      <webElementGuid>72be0dc6-ff6c-4db8-ada7-08ad32dc51be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kolkata']/parent::*</value>
      <webElementGuid>e3c54dde-7265-4529-9678-e2f4ef690ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/span</value>
      <webElementGuid>9152af49-2bc0-48ef-9fbe-0335355c473c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kolkata' or . = 'Kolkata')]</value>
      <webElementGuid>77c1d631-1746-4f1c-8d43-f379895edefa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
