<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Popular Cities_bwc__sc-ttnkwg-26 izPSOY</name>
   <tag></tag>
   <elementGuidId>34a130b4-a29a-43f1-aed0-ff34e833629c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bwc__sc-ttnkwg-26.izPSOY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;MUMBAI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ffba7e9-6090-4418-9c97-d0afd9150e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//in.bmscdn.com/m6/images/common-modules/regions/mumbai.png</value>
      <webElementGuid>109c37c7-1052-46b0-8cd1-9dde75e43596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MUMBAI</value>
      <webElementGuid>d750b27c-c293-4cd0-a5db-91ef90b0b573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bwc__sc-ttnkwg-26 izPSOY</value>
      <webElementGuid>e92264ad-55ab-496d-8da3-876e12c91365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;bwc__sc-1ihur1g-4 jxHGrI in-animation&quot;]/div[@class=&quot;bwc__sc-1ihur1g-5 gznHHe in-animation&quot;]/div[@class=&quot;bwc__sc-m1rlyj-3 bwc__sc-ttnkwg-27 kwGtup&quot;]/div[@class=&quot;bwc__sc-ttnkwg-4 Ettpg&quot;]/ul[@class=&quot;bwc__sc-ttnkwg-15 gZrltM&quot;]/li[@class=&quot;bwc__sc-ttnkwg-18 KUowN&quot;]/div[@class=&quot;bwc__sc-ttnkwg-19 gbromM&quot;]/div[@class=&quot;bwc__sc-ttnkwg-17 gvzyfS&quot;]/img[@class=&quot;bwc__sc-ttnkwg-26 izPSOY&quot;]</value>
      <webElementGuid>872ae759-d759-4a00-9d5a-b97254904a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li/div/div/img</value>
      <webElementGuid>f491d2df-860f-4183-853f-4af2ec38f6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MUMBAI']</value>
      <webElementGuid>9a201b07-21b6-40d6-8e2d-24bd9f1a67ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/img</value>
      <webElementGuid>78b7287e-c833-46d7-95a9-3ad94b96ce70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//in.bmscdn.com/m6/images/common-modules/regions/mumbai.png' and @alt = 'MUMBAI']</value>
      <webElementGuid>f5e7d481-6d66-4961-87e2-320bd4b5c457</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
