<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mumbai_bwc__sc-ttnkwg-26 izPSOY</name>
   <tag></tag>
   <elementGuidId>cdaad919-6bb3-4529-a25e-2ea62dd5fcb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bwc__sc-ttnkwg-19.gbromM > div.bwc__sc-ttnkwg-17.gvzyfS > img.bwc__sc-ttnkwg-26.izPSOY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;NCR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c738f92-5f29-494c-95d3-aa1d69298475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//in.bmscdn.com/m6/images/common-modules/regions/ncr.png</value>
      <webElementGuid>4d6508e6-4498-453a-94cd-8fefd4e9bbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>NCR</value>
      <webElementGuid>3c33874c-baaa-470f-936f-c41d5b77627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bwc__sc-ttnkwg-26 izPSOY</value>
      <webElementGuid>b0d30c2d-cf2c-4080-9604-c3d323633d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[@class=&quot;bwc__sc-1ihur1g-4 jxHGrI in-animation&quot;]/div[@class=&quot;bwc__sc-1ihur1g-5 gznHHe in-animation&quot;]/div[@class=&quot;bwc__sc-m1rlyj-3 bwc__sc-ttnkwg-27 kwGtup&quot;]/div[@class=&quot;bwc__sc-ttnkwg-4 Ettpg&quot;]/ul[@class=&quot;bwc__sc-ttnkwg-15 gZrltM&quot;]/li[@class=&quot;bwc__sc-ttnkwg-18 KUowN&quot;]/div[@class=&quot;bwc__sc-ttnkwg-19 gbromM&quot;]/div[@class=&quot;bwc__sc-ttnkwg-17 gvzyfS&quot;]/img[@class=&quot;bwc__sc-ttnkwg-26 izPSOY&quot;]</value>
      <webElementGuid>6605b810-646c-4aa0-9a31-0f3667165034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[3]/ul/li[2]/div/div/img</value>
      <webElementGuid>c3b31f9d-4cba-4c1d-80f9-a166c425ce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='NCR']</value>
      <webElementGuid>ecf0873f-c60a-4757-ab8b-b5ce717d1cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/img</value>
      <webElementGuid>d926cfe3-de30-4704-b685-7aef23709ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//in.bmscdn.com/m6/images/common-modules/regions/ncr.png' and @alt = 'NCR']</value>
      <webElementGuid>1d8c7d17-5587-4073-b119-529efe166afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
